### ISSUE TITLE
[Linux] build broken due to fmod (itself broken ...)

### ISSUE THREAD

**Issue by ebachard** [karimnaaji/live-glsl#7]
Hi,

Trying to build live-glsl on Linux, it looks like it is not buildable

1st issue : the CXX_FLAGS are not the best one, and on Linux, there is a missing ```-DGL_GLEXT_PROTOTYPES```

See the attached file (just FYI, and will probably need to be adapted for other OS) :

[diff.diff.txt](https://github.com/karimnaaji/live-glsl/files/1585778/diff.diff.txt)

2nd issue : 
```
[100%] Linking CXX executable live-glsl.out
../lib/precompiled/libfmodex.dylib: file not recognized: Format de fichier non reconnu
collect2: error: ld returned 1 exit status
CMakeFiles/live-glsl.out.dir/build.make:236 : la recette pour la cible « live-glsl.out » a échouée
make[2]: *** [live-glsl.out] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/live-glsl.out.dir/all » a échouée
make[1]: *** [CMakeFiles/live-glsl.out.dir/all] Erreur 2

```

Is there realy a good reason to use fmod ?  This is not free and probably worse ...

**Comment by karimnaaji** [comment]
Hey,

I have never tried to build it on linux, it would probably need some work before building out of the box. It shouldn't be too hard though.

> Is there realy a good reason to use fmod ? This is not free and probably worse ...

It is a fairly good library used for a lot of projects. This a a non-commercial software, so it should be free https://www.fmod.com/licensing
Probably worse than what? This dependency build-specific and remove this dependency for linux only. I am also fine with removing that dependency to have more platform support.

Just pushed a branch not using fmod, make a pull request if you manage to build it on Linux to this branch and i'll merge in master https://github.com/karimnaaji/live-glsl/tree/remove-fmod

Thanks
